api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views
from django.urls import path
from . import views

urlpatterns = [
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('index/', views.IndexView.as_view(), name='index_page'),
]

django_books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django_books_app.views import SignUpView, UserDetailedView
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("django_books_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('martor/', include('martor.urls')),
    path('profile/<int:pk>', UserDetailedView.as_view(), name='user_detail'),
    path('api/', include('api.urls'))
]

# if settings.DEBUG: # new
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_books_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator
from martor.models import MartorField
from django.db.models.signals import m2m_changed
from django.core.exceptions import ValidationError


class Author(models.Model):
    name = models.CharField(max_length=255, blank=False, unique=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    book = models.ForeignKey('Book', blank=False, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=False)
    review_text = models.TextField(max_length=1000, blank=False, validators=[MinLengthValidator(200)])
    create_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('review_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    review = models.ForeignKey('Review', on_delete=models.CASCADE, blank=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    comment_text = MartorField()

    def get_absolute_url(self):
        return reverse('review_list', kwargs={'pk': self.review.pk})

    def __str__(self):
        return self.comment_text


class Book(models.Model):
    title = models.CharField(max_length=255, blank=False, unique=True)
    authors = models.ManyToManyField('Author', blank=False)
    add_date = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cover_img = models.ImageField(upload_to='images/', default='images/default_image.png')
    description = models.TextField(max_length=2000, validators=[MinLengthValidator(100)], blank=False)
    rating = models.IntegerField(default=1, validators=[MaxValueValidator(10), MinValueValidator(1)])

    class Meta:
        ordering = ['-id']

    def check_for_file(self):
        try:
            file = self.cover_img.file
            return True
        except FileNotFoundError:
            return False

    def __str__(self):
        return self.title


def authors_check(sender, **kwargs):
    if kwargs['instance'].authors.count() > 3:
        kwargs['instance'].delete()
        raise ValidationError("You can't assign more than three authors")


m2m_changed.connect(authors_check, sender=Book.authors.through)

templates/author_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head%}
{% endblock %}
{% block content %}
    <div class="container-md">
        <h1>Enter author name</h1>
        <hr>
        <form class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-primary" type="submit">Add author</button>
            <a class="btn btn-secondary" href="{% url 'book_create' %}" role="button">Back</a>
        </form>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    {% block head %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Books</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main_page' %}">Home <span class="sr-only">(current)</span></a>
            </li>
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="#">Link</a>#}
{#            </li>#}
            {% if perms.django_books_app.add_review %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Manage
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if perms.django_books_app.add_book %}
                            <a href={% url 'book_create' %} class="dropdown-item">Add Book</a>
                        {% endif %}
                        {% if perms.django_books_app.add_book %}
                            <a href={% url 'book_list' %} class="dropdown-item">Manage Books</a>
                        {% endif %}
                        {% if perms.django_books_app.add_review %}
                            <a href={% url 'review_list' %} class="dropdown-item">Manage Reviews</a>
                        {% endif %}
                    </div>
                </li>
            {% endif %}
            <li class="nav-item">
                <a href="#" class="nav-link disabled">Hi {{ user }}</a>
            </li>
        </ul>
            <form class="form-inline my-2 my-lg-0 mr-sm-2" method="get" action={% url 'search_results' %}>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        <a class="btn btn-sd btn-outline-dark mr-sm-2" href="{% url 'logout' %}">Log out</a>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/book_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head%}
{% endblock %}
{% block content %}
    <div class="container-md">
        <h1>Delete {{ book.title }}?</h1>
        <hr>
        <form class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-danger" type="submit">Delete</button>
            <a class="btn btn-secondary" href="{% url 'book_list' %}" role="button">Back</a>
        </form>
    </div>
{% endblock %}

templates/book_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 class="wg-light">Enter title and descriptions of the book</h1>
        <hr>
        <form class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-primary" type="submit">Publish</button>

            <a class="btn btn-secondary" href={% url 'author_create' %} role="button" aria-pressed="true">Add author</a>
        </form>
        <br><hr>
    </div>
{% endblock %}

templates/book_detail.html
{% extends 'base.html' %}
{% block head%}
    <title>Index Page</title>
{% endblock %}
{% block content %}
    <br>
    <div class="container">
        <div class="row">
            <div col-md-8>
                <div class="card mb-3 border rounded shadow-sm overflow-hidden">
                    {% if book.check_for_file %}
                        <img src={{ book.cover_img.url }} width="200" height="250">
                    {% else %}
                        <img src={{ book.cover_img}} width="200" height="250">
                    {% endif %}
                </div>
            </div>
            <div class="col-md-8 ml-5">
                <h4 class="card-title">{{ book.title }}</h4>
                <p>Authors:</p>
                {% for author in book.authors.all %}
                    <p class="card-text">{{ author }}</p>
                {% endfor %}
                <p>Added by: {{ book.added_by }}</p>
                <hr>
                <p>{{ book.description }}</p>
                <hr>
                <br>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a class="btn btn-primary" href={% url 'review_per_book_list' pk=book.pk%} role="button" aria-pressed="true">See reviews</a>
                    {% if perms.django_books_app.add_review %}
                        <a class="btn btn-primary" href={% url 'review_create' pk=book.pk%} role="button" aria-pressed="true">Write a review</a>
                    {% endif %}
                    {% if perms.django_books_app.add_book %}
                        <a class="btn btn-primary" href={% url 'book_update' pk=book.pk %} role="button" aria-pressed="true">Edit</a>
                    {% endif %}
                    {% if perms.django_books_app.delete_book %}
                        <a class="btn btn-primary" href={% url 'book_delete' pk=book.pk %} role="button" aria-pressed="true">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/book_list.html
{% extends 'base.html' %}
{% block head%}
    <title>Index Page</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h1>Manage your books</h1>
        <hr>
        {% for book in book_list %}
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ book.title}}</h5>
                            {% for author in book.authors.all %}
                                <p style="display:inline" class="card-text">{{ author }}</p>
                            {% endfor %}
                            {#                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>#}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="card-body float-right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-primary" href={% url 'book_detail' pk=book.pk %} role="button" aria-pressed="true">View</a>
                                {% if perms.django_books_app.change_book %}
                                    <a class="btn btn-primary" href={% url 'book_update' pk=book.pk %} role="button" aria-pressed="true">Edit</a>
                                {% endif %}
                                {% if perms.django_books_app.delete_book %}
                                    <a class="btn btn-primary" href={% url 'book_delete' pk=book.pk %} role="button" aria-pressed="true">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
        <hr>
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

templates/book_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 class="wg-light">Enter title and descriptions of the book</h1>
        <hr>
        <form class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-primary" type="submit">Update</button>

            <a class="btn btn-secondary" href={% url 'author_create' %} role="button" aria-pressed="true">Add author</a>
        </form>
        <br><hr>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block head%}
    <title>Index Page</title>
{% endblock %}
{% block content %}
    <h1>Index page</h1>
{% endblock %}

templates/main_page.html
{% extends 'base.html' %}
{% load static %}
{% block head%}
    <title>Books</title>
{% endblock %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Books</h1>
                <p class="lead text-muted">Lorem ipsum dolor sit amet,
                    consectetur adipiscing elit. Donec condimentum,
                    dolor et commodo interdum, nisi mi ornare lacus,
                    at scelerisque diam dui in risus. Sed vitae
                    efficitur lectus, mattis viverra lorem.</p>
            </div>
        </div>
    </section>
    <div class="album">
        <div class="container">
            <div class="row">
                {% for book in book_list %}
                    <div class="col-md-6">
                        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <strong class="d-inline-block mb-2 text-success">New</strong>
                                <h3 class="mb-0">{{ book.title|truncatechars:17}}</h3>
                                <div class="mb-1 text-muted">{{ book.add_date|date:'M d' }}</div>
                                <p class="card-text mb-auto">{{ book.description|truncatechars:80}}</p>
                                <a href={% url 'book_detail' pk=book.pk %} class="stretched-link">Continue reading</a>
                            </div>
                            <div class="col-auto d-none d-lg-block">
                                {% if book.check_for_file %}
                                    <img src={{ book.cover_img.url }} width="200" height="250">
                                {% else %}
                                    <img src={{ book.cover_img}} width="200" height="250">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <h1 class="fw-light text-center">Results not found</h1>
                {% endfor %}
            </div>
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a></li>
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

{% endblock %}

templates/review_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h1>Write review for {{ book.title }}</h1>
        <hr>
        <form class="form-horizontal form_middle" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-primary" type="submit">Publish</button>
        </form>
    </div>
{% endblock %}

templates/review_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load martortags %}
{% block head%}
    <title>Review</title>

    <link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'plugins/css/bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
    <link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h1>Review for "{{ review.book}}" - {{ review.title }}    </h1>
        <p>Published {{ review.create_date|date:'M d, Y' }} by {{ review.author }}</p>
        <hr>
        <p>{{ review.review_text }}</p>
        <hr>
        <div class="container">
            {% for i in comments %}
                <div class="card mb-3">
                    <div class="card-header">
                        <p>By <a href={% url 'user_detail' pk=i.author.pk %}>{{ i.author }}</a></p>
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <div class="martor-preview">
                                {{ i.comment_text|safe_markdown }}
                            </div>
                            <footer class="blockquote-footer">{{ i.create_date|date:'M d,Y' }}</footer>
                        </blockquote>
                    </div>
                </div>
            {% endfor %}
            <form class='form' method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    </div>

    <script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'martor/js/martor.bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
    <script>
        $('.martor-preview pre').each(function(i, block){
            hljs.highlightBlock(block);
        });
    </script>

{% endblock %}

templates/review_list.html
{% extends 'base.html' %}
{% block head%}
    <title>Index Page</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h1>List of reviews</h1>
        <hr>
    </div>
    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            {% for review in review_list %}
                <div class="col-md-4">
                    <br>
                    <h3>{{ review.title|truncatechars:22 }}</h3>
                    <p>{{ review.review_text|truncatechars:200 }}</p>
                    <p>Added:   {{ review.create_date|date:'M d Y' }} by {{ review.author }}</p>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a class="btn btn-primary" href={% url 'review_detail'  pk=review.pk%} role="button">View details</a>
                        {% if perms.django_books_app.change_review %}
                            <a class="btn btn-primary" href={% url 'review_update'  pk=review.pk%} role="button">Update</a>
                        {% endif %}
                        {% if perms.django_books_app.delete_review %}
                            <a class="btn btn-primary" href={% url 'review_delete'  pk=review.pk%} role="button">Delete</a>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                    <h2 >No reviews yet</h2>
            {% endfor %}
        </div>
        <hr>
    </div>
{% endblock %}

templates/review_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 class="wg-light">Enter title and descriptions of the book</h1>
        <hr>
        <form class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn btn-primary" type="submit">Update</button>
        </form>
        <br><hr>
    </div>
{% endblock %}

templates/search_list.html
{% extends 'base.html' %}
{% block head%}
    <title>Index Page</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h1>Search results for: {{ query }}</h1>
        <hr>
        {% for book in book_list %}
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ book.title}}</h5>
                            {% for author in book.authors.all %}
                                <p style="display:inline" class="card-text">{{ author }}</p>
                            {% endfor %}
                            {#                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>#}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="card-body float-right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a class="btn btn-primary" href={% url 'book_detail' pk=book.pk %} role="button" aria-pressed="true">View</a>
                                {% if perms.django_books_app.change_book %}
                                    <a class="btn btn-primary" href={% url 'book_update' pk=book.pk %} role="button" aria-pressed="true">Edit</a>
                                {% endif %}
                                {% if perms.django_books_app.delete_book %}
                                    <a class="btn btn-primary" href={% url 'book_delete' pk=book.pk %} role="button" aria-pressed="true">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        {% endfor %}
        <hr>
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1&q={{ query }}">First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&q={{ query }}">Previous</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ query }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&q={{ query }}">Last</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}